# Generated by Django 4.2.3 on 2025-01-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Present',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='presents/', verbose_name='Presente')),
            ],
        ),
    ]
